//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvergentSeries.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConvergentSeries.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfOneLineOfHelpList xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;OneLineOfHelpList&gt;
        ///    &lt;Function&gt;+ − * /&lt;/Function&gt;
        ///    &lt;Description&gt;Addition, subtraction, multiplication, division&lt;/Description&gt;
        ///  &lt;/OneLineOfHelpList&gt;
        ///  &lt;OneLineOfHelpList&gt;
        ///    &lt;Function&gt;( )&lt;/Function&gt;
        ///    &lt;Description&gt;Grouping brackets&lt;/Description&gt;
        ///  &lt;/OneLineOfHelpList&gt;
        ///  &lt;OneLineOfHelpList&gt;
        ///    &lt;Function&gt;abs()&lt;/Function&gt;
        ///   [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string en_Eng {
            get {
                return ResourceManager.GetString("en_Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ICSharpCode_AvalonEdit {
            get {
                object obj = ResourceManager.GetObject("ICSharpCode_AvalonEdit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;doc&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;ICSharpCode.AvalonEdit&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:ICSharpCode.AvalonEdit.AvalonEditCommands&quot;&gt;
        ///      &lt;summary&gt;
        ///            Custom commands for AvalonEdit.
        ///            &lt;/summary&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;F:ICSharpCode.AvalonEdit.AvalonEditCommands.ConvertLeadingSpacesToTabs&quot;&gt;
        ///      &lt;summary&gt;
        ///            Converts leading spaces to tabs in the selected lines (or the whole document if the selection i [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ICSharpCode_AvalonEdit1 {
            get {
                return ResourceManager.GetString("ICSharpCode_AvalonEdit1", resourceCulture);
            }
        }
    }
}
